# This workflow will apply the terraform scripts which would deploy the recquied infrastructure and the startup-sample-app

name: Terraform plan

on:
  
  pull_request:
    branches: [ master ]
    
env:
  TF_VERSION: 1.0.9
  environment: dev
  organization: bcgov
  PR_BRANCH: ${{ github.head_ref }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    
        
    steps:
      - name: checkout the repo and building the Backend    
        uses: actions/checkout@v2    
        
      - name: setting variables
        run: | 
             cat <<EOF > dev.auto.tfvars
             cat dev.auto.tfvars
             echo "Pull request's base branch is: ${PR_BRANCH}"
             BRANCH_NAME = "${{ env.PR_BRANCH }}"
             EOF

    
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TF_VERSION }}
            cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Deploying startup-sample-project using terraform
        uses: hashicorp/setup-terraform@v1
        with:
           args: -var-file dev.auto.tfvars
      - run: |
            cd terraform/
            cat <<EOF > backend.hcl
            organization = "${{ env.organization }}"
            workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-ssp-vm" }
            EOF
            
            terraform init -backend-config=backend.hcl
            terraform apply -auto-approve
