# This workflow will apply the terraform scripts which would deploy the recquied infrastructure and the startup-sample-app

name: Terraform plan

on:
  
  pull_request:
    branches: [ master ]
    
env:
  TF_VERSION: 1.0.9
  environment: dev
  organization: bcgov
  branch_name: GITHUB_HEAD_REF
jobs:
  build:

    runs-on: ubuntu-latest

    
        
    steps:
      - name: checkout the repo and building the Backend    
        uses: actions/checkout@v2    
        
      - name: setting variables
        run: | 
              
               cat <<EOF > dev.auto.tfvars
               branch_name="${{ env.branch_name }}"
               echo branch_name
               EOF

    
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ env.TF_VERSION }}
            cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Deploying startup-sample-project using terraform
        run: |
            cd terraform/
            cat <<EOF > backend.hcl
            organization = "${{ env.organization }}"
            workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-ssp-vm" }
            EOF
            
            terraform init -backend-config=backend.hcl
            terraform plan 
