# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
        - uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: ${{ env.TF_VERSION }}
            cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

        - name: Deploying back-end using terraform
          run: |
            cd terraform
            cat <<EOF > backend.hcl
            organization = "${{ env.organization }}"
            workspaces { name = "${{ secrets.LICENCEPLATE }}-${{ env.environment }}-backend" }
            EOF
            
            terraform init -backend-config=backend.hcl
            terraform apply -auto-approve
